// Copyright 2017 The go-github AUTHORS. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by gen-accessors; DO NOT EDIT.
// Instead, please run "go generate ./..." as described here:
// https://github.com/google/go-github/blob/master/CONTRIBUTING.md#submitting-a-patch

package nhl

// GetBirthCity returns the BirthCity field.
func (p *Player) GetBirthCity() *Player_BirthCity {
	if p == nil {
		return nil
	}
	return p.BirthCity
}

// GetBirthCountry returns the BirthCountry field if it's non-nil, zero value otherwise.
func (p *Player) GetBirthCountry() string {
	if p == nil || p.BirthCountry == nil {
		return ""
	}
	return *p.BirthCountry
}

// GetBirthDate returns the BirthDate field if it's non-nil, zero value otherwise.
func (p *Player) GetBirthDate() string {
	if p == nil || p.BirthDate == nil {
		return ""
	}
	return *p.BirthDate
}

// GetBirthStateProvince returns the BirthStateProvince field.
func (p *Player) GetBirthStateProvince() *Player_BirthStateProvince {
	if p == nil {
		return nil
	}
	return p.BirthStateProvince
}

// GetCareerTotals returns the CareerTotals field.
func (p *Player) GetCareerTotals() *Player_CareerTotals {
	if p == nil {
		return nil
	}
	return p.CareerTotals
}

// GetCurrentTeamAbbrev returns the CurrentTeamAbbrev field if it's non-nil, zero value otherwise.
func (p *Player) GetCurrentTeamAbbrev() string {
	if p == nil || p.CurrentTeamAbbrev == nil {
		return ""
	}
	return *p.CurrentTeamAbbrev
}

// GetCurrentTeamId returns the CurrentTeamId field if it's non-nil, zero value otherwise.
func (p *Player) GetCurrentTeamId() int {
	if p == nil || p.CurrentTeamId == nil {
		return 0
	}
	return *p.CurrentTeamId
}

// GetCurrentTeamRoster returns the CurrentTeamRoster slice if it's non-nil, nil otherwise.
func (p *Player) GetCurrentTeamRoster() []*Player {
	if p == nil || p.CurrentTeamRoster == nil {
		return nil
	}
	return p.CurrentTeamRoster
}

// GetDraftDetails returns the DraftDetails field.
func (p *Player) GetDraftDetails() *Player_DraftDetails {
	if p == nil {
		return nil
	}
	return p.DraftDetails
}

// GetFeaturedStats returns the FeaturedStats field.
func (p *Player) GetFeaturedStats() *Player_FeaturedStats {
	if p == nil {
		return nil
	}
	return p.FeaturedStats
}

// GetFirstName returns the FirstName field.
func (p *Player) GetFirstName() *Player_FirstName {
	if p == nil {
		return nil
	}
	return p.FirstName
}

// GetFullTeamName returns the FullTeamName field.
func (p *Player) GetFullTeamName() *Player_FullTeamName {
	if p == nil {
		return nil
	}
	return p.FullTeamName
}

// GetHeadshot returns the Headshot field if it's non-nil, zero value otherwise.
func (p *Player) GetHeadshot() string {
	if p == nil || p.Headshot == nil {
		return ""
	}
	return *p.Headshot
}

// GetHeightInCentimeters returns the HeightInCentimeters field if it's non-nil, zero value otherwise.
func (p *Player) GetHeightInCentimeters() int {
	if p == nil || p.HeightInCentimeters == nil {
		return 0
	}
	return *p.HeightInCentimeters
}

// GetHeightInInches returns the HeightInInches field if it's non-nil, zero value otherwise.
func (p *Player) GetHeightInInches() int {
	if p == nil || p.HeightInInches == nil {
		return 0
	}
	return *p.HeightInInches
}

// GetHeroImage returns the HeroImage field if it's non-nil, zero value otherwise.
func (p *Player) GetHeroImage() string {
	if p == nil || p.HeroImage == nil {
		return ""
	}
	return *p.HeroImage
}

// GetInHHOF returns the InHHOF field if it's non-nil, zero value otherwise.
func (p *Player) GetInHHOF() int {
	if p == nil || p.InHHOF == nil {
		return 0
	}
	return *p.InHHOF
}

// GetInTop100AllTime returns the InTop100AllTime field if it's non-nil, zero value otherwise.
func (p *Player) GetInTop100AllTime() int {
	if p == nil || p.InTop100AllTime == nil {
		return 0
	}
	return *p.InTop100AllTime
}

// GetIsActive returns the IsActive field if it's non-nil, zero value otherwise.
func (p *Player) GetIsActive() bool {
	if p == nil || p.IsActive == nil {
		return false
	}
	return *p.IsActive
}

// GetLast5Games returns the Last5Games slice if it's non-nil, nil otherwise.
func (p *Player) GetLast5Games() []*Player_Game {
	if p == nil || p.Last5Games == nil {
		return nil
	}
	return p.Last5Games
}

// GetLastName returns the LastName field.
func (p *Player) GetLastName() *Player_LastName {
	if p == nil {
		return nil
	}
	return p.LastName
}

// GetPlayerId returns the PlayerId field if it's non-nil, zero value otherwise.
func (p *Player) GetPlayerId() int {
	if p == nil || p.PlayerId == nil {
		return 0
	}
	return *p.PlayerId
}

// GetPlayerSlug returns the PlayerSlug field if it's non-nil, zero value otherwise.
func (p *Player) GetPlayerSlug() string {
	if p == nil || p.PlayerSlug == nil {
		return ""
	}
	return *p.PlayerSlug
}

// GetPosition returns the Position field if it's non-nil, zero value otherwise.
func (p *Player) GetPosition() string {
	if p == nil || p.Position == nil {
		return ""
	}
	return *p.Position
}

// GetSeasonTotals returns the SeasonTotals slice if it's non-nil, nil otherwise.
func (p *Player) GetSeasonTotals() []*Player_Total {
	if p == nil || p.SeasonTotals == nil {
		return nil
	}
	return p.SeasonTotals
}

// GetShootsCatches returns the ShootsCatches field if it's non-nil, zero value otherwise.
func (p *Player) GetShootsCatches() string {
	if p == nil || p.ShootsCatches == nil {
		return ""
	}
	return *p.ShootsCatches
}

// GetShopLink returns the ShopLink field if it's non-nil, zero value otherwise.
func (p *Player) GetShopLink() string {
	if p == nil || p.ShopLink == nil {
		return ""
	}
	return *p.ShopLink
}

// GetSweaterNumber returns the SweaterNumber field if it's non-nil, zero value otherwise.
func (p *Player) GetSweaterNumber() int {
	if p == nil || p.SweaterNumber == nil {
		return 0
	}
	return *p.SweaterNumber
}

// GetTeamLogo returns the TeamLogo field if it's non-nil, zero value otherwise.
func (p *Player) GetTeamLogo() string {
	if p == nil || p.TeamLogo == nil {
		return ""
	}
	return *p.TeamLogo
}

// GetTwitterLink returns the TwitterLink field if it's non-nil, zero value otherwise.
func (p *Player) GetTwitterLink() string {
	if p == nil || p.TwitterLink == nil {
		return ""
	}
	return *p.TwitterLink
}

// GetWatchLink returns the WatchLink field if it's non-nil, zero value otherwise.
func (p *Player) GetWatchLink() string {
	if p == nil || p.WatchLink == nil {
		return ""
	}
	return *p.WatchLink
}

// GetWeightInKilograms returns the WeightInKilograms field if it's non-nil, zero value otherwise.
func (p *Player) GetWeightInKilograms() int {
	if p == nil || p.WeightInKilograms == nil {
		return 0
	}
	return *p.WeightInKilograms
}

// GetWeightInPounds returns the WeightInPounds field if it's non-nil, zero value otherwise.
func (p *Player) GetWeightInPounds() int {
	if p == nil || p.WeightInPounds == nil {
		return 0
	}
	return *p.WeightInPounds
}

// GetDefault returns the Default field if it's non-nil, zero value otherwise.
func (p *Player_BirthCity) GetDefault() string {
	if p == nil || p.Default == nil {
		return ""
	}
	return *p.Default
}

// GetDefault returns the Default field if it's non-nil, zero value otherwise.
func (p *Player_BirthStateProvince) GetDefault() string {
	if p == nil || p.Default == nil {
		return ""
	}
	return *p.Default
}

// GetPlayoffs returns the Playoffs field.
func (p *Player_CareerTotals) GetPlayoffs() *Player_Total {
	if p == nil {
		return nil
	}
	return p.Playoffs
}

// GetRegularSeason returns the RegularSeason field.
func (p *Player_CareerTotals) GetRegularSeason() *Player_Total {
	if p == nil {
		return nil
	}
	return p.RegularSeason
}

// GetOverallPick returns the OverallPick field if it's non-nil, zero value otherwise.
func (p *Player_DraftDetails) GetOverallPick() int {
	if p == nil || p.OverallPick == nil {
		return 0
	}
	return *p.OverallPick
}

// GetPickInRound returns the PickInRound field if it's non-nil, zero value otherwise.
func (p *Player_DraftDetails) GetPickInRound() int {
	if p == nil || p.PickInRound == nil {
		return 0
	}
	return *p.PickInRound
}

// GetRound returns the Round field if it's non-nil, zero value otherwise.
func (p *Player_DraftDetails) GetRound() int {
	if p == nil || p.Round == nil {
		return 0
	}
	return *p.Round
}

// GetTeamAbbrev returns the TeamAbbrev field if it's non-nil, zero value otherwise.
func (p *Player_DraftDetails) GetTeamAbbrev() string {
	if p == nil || p.TeamAbbrev == nil {
		return ""
	}
	return *p.TeamAbbrev
}

// GetYear returns the Year field if it's non-nil, zero value otherwise.
func (p *Player_DraftDetails) GetYear() int {
	if p == nil || p.Year == nil {
		return 0
	}
	return *p.Year
}

// GetPlayoffs returns the Playoffs field.
func (p *Player_FeaturedStats) GetPlayoffs() *Player_FeaturedTotals {
	if p == nil {
		return nil
	}
	return p.Playoffs
}

// GetRegularSesason returns the RegularSesason field.
func (p *Player_FeaturedStats) GetRegularSesason() *Player_FeaturedTotals {
	if p == nil {
		return nil
	}
	return p.RegularSesason
}

// GetSeason returns the Season field if it's non-nil, zero value otherwise.
func (p *Player_FeaturedStats) GetSeason() int {
	if p == nil || p.Season == nil {
		return 0
	}
	return *p.Season
}

// GetCareer returns the Career field.
func (p *Player_FeaturedTotals) GetCareer() *Player_Total {
	if p == nil {
		return nil
	}
	return p.Career
}

// GetSubSeason returns the SubSeason field.
func (p *Player_FeaturedTotals) GetSubSeason() *Player_Total {
	if p == nil {
		return nil
	}
	return p.SubSeason
}

// GetDefault returns the Default field if it's non-nil, zero value otherwise.
func (p *Player_FirstName) GetDefault() string {
	if p == nil || p.Default == nil {
		return ""
	}
	return *p.Default
}

// GetCS returns the CS field if it's non-nil, zero value otherwise.
func (p *Player_FullTeamName) GetCS() string {
	if p == nil || p.CS == nil {
		return ""
	}
	return *p.CS
}

// GetDE returns the DE field if it's non-nil, zero value otherwise.
func (p *Player_FullTeamName) GetDE() string {
	if p == nil || p.DE == nil {
		return ""
	}
	return *p.DE
}

// GetDefault returns the Default field if it's non-nil, zero value otherwise.
func (p *Player_FullTeamName) GetDefault() string {
	if p == nil || p.Default == nil {
		return ""
	}
	return *p.Default
}

// GetFI returns the FI field if it's non-nil, zero value otherwise.
func (p *Player_FullTeamName) GetFI() string {
	if p == nil || p.FI == nil {
		return ""
	}
	return *p.FI
}

// GetFR returns the FR field if it's non-nil, zero value otherwise.
func (p *Player_FullTeamName) GetFR() string {
	if p == nil || p.FR == nil {
		return ""
	}
	return *p.FR
}

// GetSK returns the SK field if it's non-nil, zero value otherwise.
func (p *Player_FullTeamName) GetSK() string {
	if p == nil || p.SK == nil {
		return ""
	}
	return *p.SK
}

// GetSV returns the SV field if it's non-nil, zero value otherwise.
func (p *Player_FullTeamName) GetSV() string {
	if p == nil || p.SV == nil {
		return ""
	}
	return *p.SV
}

// GetAssists returns the Assists field if it's non-nil, zero value otherwise.
func (p *Player_Game) GetAssists() int {
	if p == nil || p.Assists == nil {
		return 0
	}
	return *p.Assists
}

// GetCommonName returns the CommonName field.
func (p *Player_Game) GetCommonName() *Player_Game_CommonName {
	if p == nil {
		return nil
	}
	return p.CommonName
}

// GetDecision returns the Decision field if it's non-nil, zero value otherwise.
func (p *Player_Game) GetDecision() string {
	if p == nil || p.Decision == nil {
		return ""
	}
	return *p.Decision
}

// GetGameDate returns the GameDate field if it's non-nil, zero value otherwise.
func (p *Player_Game) GetGameDate() string {
	if p == nil || p.GameDate == nil {
		return ""
	}
	return *p.GameDate
}

// GetGameID returns the GameID field if it's non-nil, zero value otherwise.
func (p *Player_Game) GetGameID() int {
	if p == nil || p.GameID == nil {
		return 0
	}
	return *p.GameID
}

// GetGamesStarted returns the GamesStarted field if it's non-nil, zero value otherwise.
func (p *Player_Game) GetGamesStarted() int {
	if p == nil || p.GamesStarted == nil {
		return 0
	}
	return *p.GamesStarted
}

// GetGameWinningGoals returns the GameWinningGoals field if it's non-nil, zero value otherwise.
func (p *Player_Game) GetGameWinningGoals() int {
	if p == nil || p.GameWinningGoals == nil {
		return 0
	}
	return *p.GameWinningGoals
}

// GetGoals returns the Goals field if it's non-nil, zero value otherwise.
func (p *Player_Game) GetGoals() int {
	if p == nil || p.Goals == nil {
		return 0
	}
	return *p.Goals
}

// GetGoalsAgainst returns the GoalsAgainst field if it's non-nil, zero value otherwise.
func (p *Player_Game) GetGoalsAgainst() int {
	if p == nil || p.GoalsAgainst == nil {
		return 0
	}
	return *p.GoalsAgainst
}

// GetHomeRoadFlag returns the HomeRoadFlag field if it's non-nil, zero value otherwise.
func (p *Player_Game) GetHomeRoadFlag() string {
	if p == nil || p.HomeRoadFlag == nil {
		return ""
	}
	return *p.HomeRoadFlag
}

// GetOpponentAbbrev returns the OpponentAbbrev field if it's non-nil, zero value otherwise.
func (p *Player_Game) GetOpponentAbbrev() string {
	if p == nil || p.OpponentAbbrev == nil {
		return ""
	}
	return *p.OpponentAbbrev
}

// GetOpponentCommonName returns the OpponentCommonName field.
func (p *Player_Game) GetOpponentCommonName() *Player_Game_CommonName {
	if p == nil {
		return nil
	}
	return p.OpponentCommonName
}

// GetOTGoals returns the OTGoals field if it's non-nil, zero value otherwise.
func (p *Player_Game) GetOTGoals() int {
	if p == nil || p.OTGoals == nil {
		return 0
	}
	return *p.OTGoals
}

// GetPIM returns the PIM field if it's non-nil, zero value otherwise.
func (p *Player_Game) GetPIM() int {
	if p == nil || p.PIM == nil {
		return 0
	}
	return *p.PIM
}

// GetPlusMinus returns the PlusMinus field if it's non-nil, zero value otherwise.
func (p *Player_Game) GetPlusMinus() int {
	if p == nil || p.PlusMinus == nil {
		return 0
	}
	return *p.PlusMinus
}

// GetPoints returns the Points field if it's non-nil, zero value otherwise.
func (p *Player_Game) GetPoints() int {
	if p == nil || p.Points == nil {
		return 0
	}
	return *p.Points
}

// GetPowerPlayGoals returns the PowerPlayGoals field if it's non-nil, zero value otherwise.
func (p *Player_Game) GetPowerPlayGoals() int {
	if p == nil || p.PowerPlayGoals == nil {
		return 0
	}
	return *p.PowerPlayGoals
}

// GetPowerPlayPoints returns the PowerPlayPoints field if it's non-nil, zero value otherwise.
func (p *Player_Game) GetPowerPlayPoints() int {
	if p == nil || p.PowerPlayPoints == nil {
		return 0
	}
	return *p.PowerPlayPoints
}

// GetSavePctg returns the SavePctg field.
func (p *Player_Game) GetSavePctg() *float64 {
	if p == nil {
		return nil
	}
	return p.SavePctg
}

// GetShifts returns the Shifts field if it's non-nil, zero value otherwise.
func (p *Player_Game) GetShifts() int {
	if p == nil || p.Shifts == nil {
		return 0
	}
	return *p.Shifts
}

// GetShorthandedGoals returns the ShorthandedGoals field if it's non-nil, zero value otherwise.
func (p *Player_Game) GetShorthandedGoals() int {
	if p == nil || p.ShorthandedGoals == nil {
		return 0
	}
	return *p.ShorthandedGoals
}

// GetShorthandedPoints returns the ShorthandedPoints field if it's non-nil, zero value otherwise.
func (p *Player_Game) GetShorthandedPoints() int {
	if p == nil || p.ShorthandedPoints == nil {
		return 0
	}
	return *p.ShorthandedPoints
}

// GetShots returns the Shots field if it's non-nil, zero value otherwise.
func (p *Player_Game) GetShots() int {
	if p == nil || p.Shots == nil {
		return 0
	}
	return *p.Shots
}

// GetShotsAgainst returns the ShotsAgainst field if it's non-nil, zero value otherwise.
func (p *Player_Game) GetShotsAgainst() int {
	if p == nil || p.ShotsAgainst == nil {
		return 0
	}
	return *p.ShotsAgainst
}

// GetShutouts returns the Shutouts field if it's non-nil, zero value otherwise.
func (p *Player_Game) GetShutouts() int {
	if p == nil || p.Shutouts == nil {
		return 0
	}
	return *p.Shutouts
}

// GetTeamAbbrev returns the TeamAbbrev field if it's non-nil, zero value otherwise.
func (p *Player_Game) GetTeamAbbrev() string {
	if p == nil || p.TeamAbbrev == nil {
		return ""
	}
	return *p.TeamAbbrev
}

// GetTOI returns the TOI field if it's non-nil, zero value otherwise.
func (p *Player_Game) GetTOI() string {
	if p == nil || p.TOI == nil {
		return ""
	}
	return *p.TOI
}

// GetDefault returns the Default field if it's non-nil, zero value otherwise.
func (p *Player_Game_CommonName) GetDefault() string {
	if p == nil || p.Default == nil {
		return ""
	}
	return *p.Default
}

// GetDefault returns the Default field if it's non-nil, zero value otherwise.
func (p *Player_LastName) GetDefault() string {
	if p == nil || p.Default == nil {
		return ""
	}
	return *p.Default
}

// GetAssists returns the Assists field if it's non-nil, zero value otherwise.
func (p *Player_Total) GetAssists() int {
	if p == nil || p.Assists == nil {
		return 0
	}
	return *p.Assists
}

// GetAvgToi returns the AvgToi field if it's non-nil, zero value otherwise.
func (p *Player_Total) GetAvgToi() string {
	if p == nil || p.AvgToi == nil {
		return ""
	}
	return *p.AvgToi
}

// GetFaceoffWinningPctg returns the FaceoffWinningPctg field.
func (p *Player_Total) GetFaceoffWinningPctg() *float64 {
	if p == nil {
		return nil
	}
	return p.FaceoffWinningPctg
}

// GetGamesPlayed returns the GamesPlayed field if it's non-nil, zero value otherwise.
func (p *Player_Total) GetGamesPlayed() int {
	if p == nil || p.GamesPlayed == nil {
		return 0
	}
	return *p.GamesPlayed
}

// GetGamesStarted returns the GamesStarted field if it's non-nil, zero value otherwise.
func (p *Player_Total) GetGamesStarted() int {
	if p == nil || p.GamesStarted == nil {
		return 0
	}
	return *p.GamesStarted
}

// GetGameTypeId returns the GameTypeId field if it's non-nil, zero value otherwise.
func (p *Player_Total) GetGameTypeId() int {
	if p == nil || p.GameTypeId == nil {
		return 0
	}
	return *p.GameTypeId
}

// GetGameWinningGoals returns the GameWinningGoals field if it's non-nil, zero value otherwise.
func (p *Player_Total) GetGameWinningGoals() int {
	if p == nil || p.GameWinningGoals == nil {
		return 0
	}
	return *p.GameWinningGoals
}

// GetGoals returns the Goals field if it's non-nil, zero value otherwise.
func (p *Player_Total) GetGoals() int {
	if p == nil || p.Goals == nil {
		return 0
	}
	return *p.Goals
}

// GetGoalsAgainst returns the GoalsAgainst field if it's non-nil, zero value otherwise.
func (p *Player_Total) GetGoalsAgainst() int {
	if p == nil || p.GoalsAgainst == nil {
		return 0
	}
	return *p.GoalsAgainst
}

// GetGoalsAgainstAvg returns the GoalsAgainstAvg field.
func (p *Player_Total) GetGoalsAgainstAvg() *float64 {
	if p == nil {
		return nil
	}
	return p.GoalsAgainstAvg
}

// GetLeagueAbbrev returns the LeagueAbbrev field if it's non-nil, zero value otherwise.
func (p *Player_Total) GetLeagueAbbrev() string {
	if p == nil || p.LeagueAbbrev == nil {
		return ""
	}
	return *p.LeagueAbbrev
}

// GetLosses returns the Losses field if it's non-nil, zero value otherwise.
func (p *Player_Total) GetLosses() int {
	if p == nil || p.Losses == nil {
		return 0
	}
	return *p.Losses
}

// GetOTGoals returns the OTGoals field if it's non-nil, zero value otherwise.
func (p *Player_Total) GetOTGoals() int {
	if p == nil || p.OTGoals == nil {
		return 0
	}
	return *p.OTGoals
}

// GetOTLosses returns the OTLosses field if it's non-nil, zero value otherwise.
func (p *Player_Total) GetOTLosses() int {
	if p == nil || p.OTLosses == nil {
		return 0
	}
	return *p.OTLosses
}

// GetPIM returns the PIM field if it's non-nil, zero value otherwise.
func (p *Player_Total) GetPIM() int {
	if p == nil || p.PIM == nil {
		return 0
	}
	return *p.PIM
}

// GetPlusMinus returns the PlusMinus field if it's non-nil, zero value otherwise.
func (p *Player_Total) GetPlusMinus() int {
	if p == nil || p.PlusMinus == nil {
		return 0
	}
	return *p.PlusMinus
}

// GetPoints returns the Points field if it's non-nil, zero value otherwise.
func (p *Player_Total) GetPoints() int {
	if p == nil || p.Points == nil {
		return 0
	}
	return *p.Points
}

// GetPowerPlayGoals returns the PowerPlayGoals field if it's non-nil, zero value otherwise.
func (p *Player_Total) GetPowerPlayGoals() int {
	if p == nil || p.PowerPlayGoals == nil {
		return 0
	}
	return *p.PowerPlayGoals
}

// GetPowerPlayPoints returns the PowerPlayPoints field if it's non-nil, zero value otherwise.
func (p *Player_Total) GetPowerPlayPoints() int {
	if p == nil || p.PowerPlayPoints == nil {
		return 0
	}
	return *p.PowerPlayPoints
}

// GetSavePctg returns the SavePctg field.
func (p *Player_Total) GetSavePctg() *float64 {
	if p == nil {
		return nil
	}
	return p.SavePctg
}

// GetSeason returns the Season field if it's non-nil, zero value otherwise.
func (p *Player_Total) GetSeason() int {
	if p == nil || p.Season == nil {
		return 0
	}
	return *p.Season
}

// GetSequence returns the Sequence field if it's non-nil, zero value otherwise.
func (p *Player_Total) GetSequence() int {
	if p == nil || p.Sequence == nil {
		return 0
	}
	return *p.Sequence
}

// GetShootingPctg returns the ShootingPctg field.
func (p *Player_Total) GetShootingPctg() *float64 {
	if p == nil {
		return nil
	}
	return p.ShootingPctg
}

// GetShorthandedGoals returns the ShorthandedGoals field if it's non-nil, zero value otherwise.
func (p *Player_Total) GetShorthandedGoals() int {
	if p == nil || p.ShorthandedGoals == nil {
		return 0
	}
	return *p.ShorthandedGoals
}

// GetShorthandedPoints returns the ShorthandedPoints field if it's non-nil, zero value otherwise.
func (p *Player_Total) GetShorthandedPoints() int {
	if p == nil || p.ShorthandedPoints == nil {
		return 0
	}
	return *p.ShorthandedPoints
}

// GetShots returns the Shots field if it's non-nil, zero value otherwise.
func (p *Player_Total) GetShots() int {
	if p == nil || p.Shots == nil {
		return 0
	}
	return *p.Shots
}

// GetShotsAgainst returns the ShotsAgainst field if it's non-nil, zero value otherwise.
func (p *Player_Total) GetShotsAgainst() int {
	if p == nil || p.ShotsAgainst == nil {
		return 0
	}
	return *p.ShotsAgainst
}

// GetShutouts returns the Shutouts field if it's non-nil, zero value otherwise.
func (p *Player_Total) GetShutouts() int {
	if p == nil || p.Shutouts == nil {
		return 0
	}
	return *p.Shutouts
}

// GetTeamName returns the TeamName field.
func (p *Player_Total) GetTeamName() *Player_FullTeamName {
	if p == nil {
		return nil
	}
	return p.TeamName
}

// GetTies returns the Ties field if it's non-nil, zero value otherwise.
func (p *Player_Total) GetTies() int {
	if p == nil || p.Ties == nil {
		return 0
	}
	return *p.Ties
}

// GetTimeOnIce returns the TimeOnIce field if it's non-nil, zero value otherwise.
func (p *Player_Total) GetTimeOnIce() string {
	if p == nil || p.TimeOnIce == nil {
		return ""
	}
	return *p.TimeOnIce
}

// GetWins returns the Wins field if it's non-nil, zero value otherwise.
func (p *Player_Total) GetWins() int {
	if p == nil || p.Wins == nil {
		return 0
	}
	return *p.Wins
}
